### ISSUE TITLE
EnsureAdminRights always quits the app

### ISSUE THREAD

**Issue by binboydotnet** [MartinMiles/Sifon#2]
EnsureAdminRights() in OnStart.cs: 
When current user does not have admin rights and there is attempt to elevate, it executes Application.Exit() no matter if such attempt was successful or not.

**Suggested fix**: Analyze the the business logic and make sure Application.Exit() executes only when admin rights not gained.

**Comment by MartinMiles** [comment]
The application requires admin right. 
What has been done is the whole start and first-run experiences have been re-worked, and your suggested approach is implemented.
