### ISSUE TITLE
Remoting funtionality initialization dependant on profile existence

### ISSUE THREAD

**Issue by binboydotnet** [MartinMiles/Sifon#4]
Initialization of remoting functionality is dependant on an existing profile. That throws an exception on a first app run as such profile does not exist yet.

**Suggested fix**: Architecture decision to be made how to resolve this, either:
1. Consider profile existence as conditional and provide an alternative way to handle such situation whenever it's consumed
2. Create an initial profile if none exists for initialization purpose
3. Skip remoting initialization if profile does not exist

I would recommend option 1 and introduce an extra abstraction to separate remoting and local functionality and their initialization.

**Comment by MartinMiles** [comment]
That has been fixed in the release vision (past 1.00)
